routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resources([
	'companies'		=>  'CompanyController',
	'projects'		=>	'ProjectController',
	'tasks'			=>  'TaskController',
	'posts'			=>  'PostController',
	'users'			=>  'UserController',
]);

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
use App\Project;
use App\Company;

class Company extends Model
{
    protected $fillable = [
        'name',
		'description',
		'logo',
		'user_id',
    ];

	public function projects() 
	{
		return $this->hasMany(Project::class);
	}
	
	public function companyProjects() 
	{
		$projects = Project::where('company_id', $this->id)->get();
		return $projects;
	}
	
	public function user()
	{
		return User::find($this->user_id);
	}
	
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;

class CompanyController extends Controller
{

    public function index()
    {
        $companies = Company::all();
		return view('companies.index', compact('companies'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show(Company $company)
    {
        return view('companies.show', compact('company'));
    }

    public function edit(Company $company)
    {
        //
    }

    public function update(Request $request, Company $company)
    {
        //
    }

    public function destroy(Company $company)
    {
        //
    }
}

resources/views/companies/index.blade.php
@extends('layouts.adminLTE.app')

@section('content')

<div class="content-wrapper">
	<section class="content-header">
		<h1>Companies <small>All registered companies</small></h1>
		@include('layouts.adminLTE.breadCrumb')
	</section>
    <!-- Main content -->
    <section class="content container-fluid">
		<div class="box">
			<div class="box-body">
				<table id="example2" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>ID</th>
							<th>Company Name</th>
							<th>Description</th>
							<th>Created By</th>
							<th>No. Projects</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
						@foreach($companies as $company)
						<tr>
							<td>{{ $company->id }}</td>
							<td><a href="{{ route('companies.show', $company->id) }}">{{ $company->name }}</a></td>
							<td>{{ $company->description }}</td>
							<td><a href="{{ route('users.show', $company->user_id) }}">{{ $company->user()->name }}</a></td>
							<td><a href="{{ route('companies.show', $company->id) }}">{{ count($company->companyProjects()) }} Projects (Click to view)</a></td>
							<td style="text-align: center;">
								<a href="{{ route('companies.edit', $company->id) }}"><i class="fa fa-edit"></i></a>&nbsp &nbsp
								<a href="{{ route('companies.destroy', $company->id) }}"><i class="fa fa-window-close"></i> </a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</section>
</div>
@endsection


@section('additionalCSS')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{ url('/') }}/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
@endsection


@section('additionalJS')
<!-- DataTables -->
<script src="{{ url('/') }}/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="{{ url('/') }}/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="{{ url('/') }}/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="{{ url('/') }}/bower_components/fastclick/lib/fastclick.js"></script>

<!-- AdminLTE for demo purposes -->
<script src="{{ url('/') }}/js/demo.js"></script>
<!-- page script -->
<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.adminLTE.app')

@section('content')
<div class="content-wrapper">
	<section class="content-header">
		<h1>{{ $company->name }}<small>{{ $company->description }}</small></h1>
		@include('layouts.adminLTE.breadCrumb')
	</section>
	<!-- Main content -->
	<section class="content container-fluid">
		<div class="box">
			<div class="box-body">
				<table id="example1" class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>Project Name</th>
							<th>Description</th>
							<th>Created By</th>
							<th>No. Tasks</th>
							<th>Active</th>
							<th>Progress</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($company->companyProjects() as $project)
						<tr>
							<td><a href="{{ route('projects.index', $project->id) }}">{{ $project->name }}</a></td>
							<td>{{ $project->description }}</td>
							<td><a href="{{ route('users.show', $project->user_id) }}">{{ $project->projectUser()->name }}</a></td>
							<td><a href="{{ route('projects.show', $project->id) }}">{{ count($project->projectTasks()) }} Tasks (Click to view)</a></td>
							<td>{{ $project->active }}</td>
							<td>
								<div class="progress progress-sm active">
									<div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: {{ $project->progress }}%">
										<span class="sr-only">{{ $project->progress }}% Completed</span>
									</div>
								</div>{{ $project->progress }}%</td>
							<td style="text-align: center;">
								<a href="{{ route('projects.edit', $project->id) }}"><i class="fa fa-edit"></i></a>&nbsp &nbsp
								<a href="{{ route('projects.destroy', $project->id) }}"><i class="fa fa-window-close"></i></a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
	</section>
</div>
@endsection

@section('additionalCSS')

@endsection

@section('additionalJS')

@endsection